name = "pg-cw-example-webpack5"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-01-31"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"